name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.6'
        cabal-version: '3.12'
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    - name: Test
      run: cabal test
  build:
    runs-on: windows-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.6'
        cabal-version: '3.12'
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    - name: Build
      run: cabal build
    - name: Install
      run: cabal install --installdir .
    - uses: actions/upload-artifact@v4
      with:
        name: visg-windows
        path: |
          visg.exe
  build-linux:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.6'
        cabal-version: '3.12'
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    - name: Build
      run: cabal build --enable-executable-static
    - name: Install
      run: cabal install --installdir . --enable-executable-static
    - uses: actions/upload-artifact@v4
      with:
        name: visg-linux
        path: |
          visg
